version: '2'
services:
  base:
    environment:
     - DC_NAME=kafka
    networks:
     - kafka-net

  client:
    extends:
      service: base
    environment:
     - CONSUL_CLUSTER_IPS=consul

  kafka:
    image: qnib/kafka:0.10.0.1
    extends:
      service: client
    environment:
     - FORWARD_TO_KAFKA=true
    privileged: true
