version: '2'
services:
  consul:
    image: qnib/alpn-consul
    hostname: consul
    container_name: consul
    extends:
      file: base.yml
      service: base
    environment:
     - CONSUL_BOOTSTRAP_EXPECT=1
    ports:
     - "8500:8500"

  zookeeper:
    image: qnib/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    extends:
      file: base.yml
      service: client
    ports:
     - 2181:2181

  zkui:
    image: qnib/zkui
    hostname: zkui
    container_name: zkui
    extends:
      file: base.yml
      service: client
    ports:
     - 9090:9090

  kafka:
    hostname: kafka
    container_name: kafka
    extends:
      file: base.yml
      service: kafka
    environment:
     - KAFKA_PORT=9092
    ports:
     - 9092:9092

  kafkaMgr:
    image: qnib/kafka-manager
    hostname: kafka-manager
    container_name: kafka-manager
    extends:
      file: base.yml
      service: client
    environment:
     - APPLICATION_SECRET=letmein
    ports:
     - 9000:9000
    volumes:
     - ./conf/:/kafka-manager-1.2.7/conf/

networks:
  kafka-net:
