consul:
    image: qnib/consul
    hostname: consul
    container_name: consul
    extends:
      file: base.yml
      service: base
    environment:
    - RUN_SERVER=true
    - BOOTSTRAP_CONSUL=true
    ports:
    - "8500:8500"

zkui:
    image: qnib/zkui
    hostname: zkui
    container_name: zkui
    extends:
      file: base.yml
      service: base
    links:
    - consul:consul
    ports:
    - 9090:9090
    privileged: true

zookeeper:
    image: qnib/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    extends:
      file: base.yml
      service: base
    links:
    - consul:consul
    privileged: true
    ports:
    - 2181:2181

kafkaMonitor:
    image: qnib/kafka-monitor
    hostname: kafka-monitor
    container_name: kafka-monitor
    extends:
      file: base.yml
      service: base
    environment:
    - FORWARD_TO_KAFKA=true
    links:
    - consul:consul
    - kafka0:kafka
    ports:
    - 8080:8080
    privileged: true

kafkaMgr:
    image: qnib/kafka-manager
    hostname: kafka-manager
    container_name: kafka-manager
    extends:
      file: base.yml
      service: base
    environment:
    - APPLICATION_SECRET=letmein
    ports:
    - 9000:9000
    volumes:
    - ./conf/:/kafka-manager-1.2.7/conf/
    links:
    - consul:consul
    - zookeeper:zookeeper

kafka0:
    extends:
      file: base.yml
      service: kafka
    hostname: kafka0
    environment:
    - BARE_HOST=kafka0
    links:
    - consul:consul
    - zookeeper:zookeeper

kafka1:
    extends:
      file: base.yml
      service: kafka
    environment:
    - BARE_HOST=kafka1
    hostname: kafka1
    links:
    - consul:consul
    - zookeeper:zookeeper

kafka2:
    extends:
      file: base.yml
      service: kafka
    hostname: kafka2
    environment:
    - BARE_HOST=kafka2
    links:
    - consul:consul
    - zookeeper:zookeeper
