consul:
    hostname: consul
    image: qnib/consul
    environment:
    - DC_NAME=dc1
    ports:
    - "8500:8500"
    dns: 127.0.0.1

zkui:
    hostname: zkui
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/zkui
    environment:
    - DC_NAME=dc1
    links:
    - consul:consul
    ports:
    - 9090:9090
    privileged: true

zookeeper:
    hostname: zookeeper
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/zookeeper
    environment:
    - DC_NAME=dc1
    links:
    - consul:consul
    privileged: true

kafkaMonitor:
    image: qnib/kafka-monitor
    hostname: kafka-monitor
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    environment:
    - DC_NAME=dc1
    - FORWARD_TO_KAFKA=true
    links:
    - consul:consul
    - kafka0:kafka
    ports:
    - 8080:8080
    privileged: true

kafkaMgr:
    image: sheepkiller/kafka-manager
    environment:
    - ZK_HOSTS="172.17.0.65:2181"
    - APPLICATION_SECRET=letmein 
    extra_hosts:
    - kafka0:172.17.0.121
    - kafka1:172.17.0.120
    - kafka2:172.17.0.122
    ports:
    - 9000:9000
    volumes:
    - ./conf/:/kafka-manager-1.2.7/conf/
    
kafka0:
    extends:
      file: base.yml
      service: kafka
    hostname: kafka0
    environment:
    - BARE_HOST=kafka0
    links:
    - consul:consul
    - zookeeper:zookeeper

kafka1:
    extends:
      file: base.yml
      service: kafka
    environment:
    - BARE_HOST=kafka1
    hostname: kafka1
    links:
    - consul:consul
    - zookeeper:zookeeper

kafka2:
    extends:
      file: base.yml
      service: kafka
    hostname: kafka2
    environment:
    - BARE_HOST=kafka2
    links:
    - consul:consul
    - zookeeper:zookeeper
