consul:
    hostname: consul
    image: qnib/consul
    environment:
    - DC_NAME=dc1
    ports:
    - "8500:8500"
    dns: 127.0.0.1

zkui:
    hostname: zkui
    dns: 127.0.0.1
    image: qnib/zkui
    environment:
    - DC_NAME=dc1
    links:
    - consul:consul
    ports:
    - 9090:9090
    privileged: true

zookeeper:
    hostname: zookeeper
    dns: 127.0.0.1
    image: qnib/zookeeper
    environment:
    - DC_NAME=dc1
    links:
    - consul:consul
    privileged: true

kafka0:
    hostname: kafka0
    dns: 127.0.0.1
    image: qnib/kafka
    environment:
    - DC_NAME=dc1
    - FORWARD_TO_KAFKA=true
    links:
    - consul:consul
    - zookeeper:zookeeper
    privileged: true

#kafka1:
#    hostname: kafka1
#    dns: 127.0.0.1
#    image: qnib/kafka
#    environment:
#    - DC_NAME=dc1
#    - FORWARD_TO_KAFKA=true
#    links:
#    - consul:consul
#    - zookeeper:zookeeper
#    privileged: true
